waypoints:
  - name: fp1
    frame_id: odom
    x: 1.0
    y: 0.0
    yaw: 0.0
  - name: fp2
    frame_id: odom
    x: 2.5
    y: 1.0
    yaw: 1.5708
  - name: fp3
    frame_id: odom
    x: 1.0
    y: 2.0
    yaw: 3.1416
