slam_toolbox:
  ros__parameters:
    use_sim_time: false
    mode: mapping
    map_frame_name: map
    odom_frame_name: odom
    base_frame_name: base_link
    scan_topic: /scan
    map_update_interval: 5.0
    max_laser_range: 12.0
    minimum_time_interval: 0.25
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    resolution: 0.05
    max_range: 12.0
    minimum_range: 0.2
    scan_queue_size: 10
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 4.0
    loop_match_maximum_variance_fine: 0.5
