navsat_transform:
  ros__parameters:
    frequency: 10.0
    delay: 3.0
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_utm_transform: false
    publish_filtered_gps: false
    use_odometry_yaw: false
    wait_for_datum: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map
